# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

dist: xenial
language: python
python:
  - 3.8
  - 3.7
  - 3.6

addons:
  apt:
    packages:
      - r-base
      - pandoc
      - graphviz
    update: true

before_install:
    - sudo mkdir -p /usr/local/lib/R/site-library
    - echo 'R_LIBS=/usr/local/lib/R/site-library:/usr/lib/R/library:/usr/lib/R/site-library/' > ~/.Renviron
    - cat ~/.Renviron
    - sudo chmod 2777 /usr/local/lib/R/site-library

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - Rscript wbuild/R/installRpackages.R
    - pip install -U tox-travis

# command to run tests, e.g. python setup.py test
script:
    - Rscript -e ".libPaths()"
    - Rscript -e "rownames(installed.packages())"
    - tox

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: wachutka
#  password:
#    secure: PLEASE_REPLACE_ME
#  on:
#    tags: true
#    repo: wachutka/wbuild
#    python: 2.7
